import { Blog, BlogListResponse } from '@/types/blog';

export async function getBlogs(): Promise<BlogListResponse> {
  return {
    blogs: [
      {
        id: '1',
        title: 'Understanding Modern Web Development',
        description: 'A deep dive into the latest web development trends and best practices.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Sarah Johnson',
        date: '2024-03-20',
        readTime: '5 min read',
        image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085',
      },
      {
        id: '2',
        title: 'The Future of Artificial Intelligence',
        description: 'Exploring the potential impact of AI on various industries.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Michael Chen',
        date: '2024-03-19',
        readTime: '7 min read',
        image: 'https://images.unsplash.com/photo-1555255707-c07966088b7b',
      },
      {
        id: '3',
        title: 'Sustainable Technology Practices',
        description: 'How tech companies are adopting eco-friendly solutions.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Emma Davis',
        date: '2024-03-18',
        readTime: '4 min read',
        image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09',
      },
      {
        id: '4',
        title: 'The Rise of Edge Computing',
        description: 'Understanding the shift towards edge computing architectures.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'David Wilson',
        date: '2024-03-17',
        readTime: '6 min read',
        image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa',
      },
      {
        id: '5',
        title: 'Cybersecurity Best Practices',
        description: 'Essential security measures for modern applications.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Lisa Brown',
        date: '2024-03-16',
        readTime: '8 min read',
        image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1',
      },
      {
        id: '6',
        title: 'Cloud Native Development',
        description: 'Building scalable applications for the cloud.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'James Lee',
        date: '2024-03-15',
        readTime: '5 min read',
        image: 'https://images.unsplash.com/photo-1484417894907-623942c8ee29',
      },
      {
        id: '7',
        title: 'The Evolution of DevOps',
        description: 'How DevOps practices have transformed software development.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Rachel Green',
        date: '2024-03-14',
        readTime: '6 min read',
        image: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6',
      },
      {
        id: '8',
        title: 'Microservices Architecture',
        description: 'Design patterns for building microservices-based applications.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Tom Anderson',
        date: '2024-03-13',
        readTime: '7 min read',
        image: 'https://images.unsplash.com/photo-1504384764586-bb4cdc1707b0',
      },
      {
        id: '9',
        title: 'The Future of Web3',
        description: 'Exploring decentralized web technologies and their impact.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Sophie Martinez',
        date: '2024-03-12',
        readTime: '5 min read',
        image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0',
      },
    ],
  };
}